version: '3.4'

services:
  smartmaple_mongo:
    image: mongo
    container_name: smartmaple_mongo
    ports:
      - "27017:27017"

  smartmaple_python:
    container_name: smartmaple_python
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - smartmaple_mongo